import logging
import re
import unicodedata
import spacy
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from difflib import SequenceMatcher
# Set up logging
logging.basicConfig(level=logging.INFO)

# Download necessary NLTK data files (run once)
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')

# Initialize spaCy model and NLTK lemmatizer
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    # If the model is not present, download it
    from spacy.cli import download
    download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

lemmatizer = WordNetLemmatizer()


KEYWORDS = [
    "trans woman",
    "tranny",
    "demigal",
    "kathoey",
    "demiboy",
    "demiguy",
    "LGBTQIA",
    "intersex",
    "demienby",
    "bigender",
    "futanari",
    "demimasc",
    "demigirl",
    "altersex",
    "x-gender",
    "demiflux",
    "trannies",
    "androgyne",
    "trans man",
    "cogenitor",
    "androgyny",
    "demifluid",
    "anti-male",
    "cisgender",
    "androgynos",
    "trans hate",
    "transphobi",
    "anti-trans",
    "two spirit",
    "non binary",
    "deadnaming",
    "anti-woman",
    "Transology",
    "tranvestia",
    "sex rights",
    "gender-",
    "gender-based",
    "wrong body",
    "demigender",
    "sex change",
    "anti-female",
    "transgender",
    "transsexual",
    "cass report",
    "trans woman",
    "transphobia",
    "neutral sex",
    "transphobic",
    "genderfluid",
    "misgendered",
    "androgynous",
    "trans youth",
    "sex matters",
    "genderqueer",
    "hilary cass",
    "Cass Review",
    "trans people",
    "gender queer",
    "detransition",
    "intersex man",
    "misgendering",
    "third gender",
    "trans rights",
    "trans issues",
    "gender clinic",
    "female erasure",
    "trans advocacy",
    "transmasculine",
    "gender affirming care",
    "biological man",
    "gender identity",
    "gender agnostic",
    "gender euphoria",
    "trans exclusion",
    "hermaphroditism",
    "transmedicalism",
    "gender critical",
    "trans-inclusive",
    "biological male",
    "trans community",
    "intersex people",
    "identity denial",
    "cisgender",
    "bigender person",
    "detransitioners",
    "Hormone blockers",
    "biological woman",
    "social contagion",
    "gender divisions",
    "gender dysphoria",
    "sex-based rights",
    "puberty blockers",
    "queer liberation",
    "trans breast milk",
    "single sex spaces",
    "biological female",
    "gender specialist",
    "assigned at birth",
    "genderqueer person",
    "genderqueer people",
    "adult human female",
    "conversion therapy",
    "androgynous people",
    "androgynous person",
    "men in women spaces",
    "protect women sports",
    "protect women rights",
    "men in women's spaces",
    "gender non-conforming",
    "protect women's sports",
    "protect women's rights",
    "trans identified",
    "trans rights",
    "trans discrimination",
    "intersectional feminism",
    "legal definition of sex",
    "biological essentialism",
    "assigned female at birth",
    "trans-inclusive",
    "gender-critical",
    "trans exclusionary",
    "rapid onset gender dysphoria",
    "LGB Alliance",
    "Scottish Women in sport",
    "sex matter",
    "iftcc",
    "gender critical",
    "gender ID",
    "Gender services",
    "what is a woman",
    "gender services",
    "Gender recognition",
    "cass report"
]


irrelevant_for_keywords = [
    "transe",
    # "transm",
    # "ctrans",
    # "transa",
    # "transf",
    # "strans",
    # "itrans",
    # "transp",
    # "vtrans",
    # "transl",
    # "transv",
    # "atrans",
    # "transx",
    # "transec",
    # "cotrans",
    # "intrans",
    # "transax",
    # "transac",
    # "transys",
    # "transia",
    # "transin",
    # "transom",
    # "transsc",
    # "eutrans",
    # "transly",
    # "wytrans",
    # "transam",
    # "patrans",
    # "transil",
    # "transex",
    # "transch",
    # "transas",
    # "transmo",
    # "transco",
    # "transit",
    # "sptrans",
    # "transwa",
    # "transyt",
    # "butrans",
    # "transdev",
    # "samtrans",
    # "transpor",
    # "transcad",
    # "transdec",
    # "transpec",
    # "transsec",
    # "transifs",
    # "transocm",
    # "transire",
    # "eastrans",
    # "transgas",
    # "unitrans",
    # "transord",
    # "transcap",
    # "transbus",
    # "translit",
    # "tktransr",
    # "sistrans",
    # "nestrans",
    # "transude",
    # "jictrans",
    # "transmew",
    # "transits",
    # "transron",
    # "transdiv",
    # "transman",
    # "transair",
    # "transmat",
    # "transcom",
    # "tranship",
    # "transmac",
    # "transtar",
    # "geotrans",
    # "transmod",
    # "transtec",
    # "transnow",
    # "transeat",
    # "transarc",
    # "transoms",
    # "transmit",
    # "transfer",
    # "transloc",
    # "reftrans",
    # "transims",
    # "transhab",
    # "transgaz",
    # "dextrans",
    # "transect",
    # "transadf",
    # "transact",
    # "transume",
    # "transyte",
    # "transkei",
    # "transcur",
    # "transpac",
    # "westrans",
    # "transept",
    # "avitrans",
    # "transltr",
    # "sustrans",
    # "filtrans",
    # "caltrans",
    # "saftrans",
    # "reptrans",
    # "transval",
    # "diptrans",
    # "sectrans",
    # "transmux",
    # "transnet",
    # "navtrans",
    # "transfix",
    # "transecur",
    # "transires",
    # "transproc",
    # "transomed",
    # "transtrum",
    # "transvert",
    # "transfers",
    # "cinctrans",
    # "transgrid",
    # "cttransit",
    # "transfuge",
    # "transenna",
    # "transterm",
    # "wordtrans",
    # "transcona",
    # "capstrans",
    # "transmute",
    # "transmeta",
    # "transmits",
    # "tranships",
    # "actransit",
    # "transapex",
    # "transpare",
    # "transfect",
    # "transport",
    # "transship",
    # "transform",
    # "omnitrans",
    # "transflux",
    # "itransact",
    # "sumatrans",
    # "transhape",
    # "transpire",
    # "transvaal",
    # "transcend",
    # "transjoik",
    # "transacts",
    # "transmove",
    # "pinftrans",
    # "transpile",
    # "mototrans",
    # "translate",
    # "transitus",
    # "transsect",
    # "transenne",
    # "transgene",
    # "transvest",
    # "transtech",
    # "transhelp",
    # "transwave",
    # "transfuse",
    # "transfare",
    # "transuded",
    # "transepts",
    # "transaxle",
    # "transitio",
    # "translohr",
    # "transcode",
    # "transalta",
    # "duratrans",
    # "transects",
    # "transitex",
    # "transcaer",
    # "transfund",
    # "transcyte",
    # "helitrans",
    # "transduce",
    # "sinotrans",
    # "transpose",
    # "transmete",
    # "transcomm",
    # "transumpt",
    # "translink",
    # "transeunt",
    # "transonic",
    # "transient",
    # "transited",
    # "transpass",
    # "transcare",
    # "transcoop",
    # "transwerk",
    # "transudes",
    # "transvans",
    # "transaero",
    # "transferee",
    # "transtrand",
    # "transducin",
    # "transiting",
    # "transbasal",
    # "transprose",
    # "transuding",
    # "transurban",
    # "transitory",
    # "transfuses",
    # "transcarga",
    # "transverse",
    # "transdural",
    # "transcrime",
    # "transexual",
    # "transacted",
    # "transtario",
    # "transmural",
    # "transposon",
    # "transcript",
    # "transacter",
    # "transaxial",
    # "transected",
    # "transposal",
    # "transworld",
    # "transbrake",
    # "transduced",
    # "transexion",
    # "transposer",
    # "transferer",
    # "transplace",
    # "transferor",
    # "translates",
    # "transmeate",
    # "transolver",
    # "transferre",
    # "transitive",
    # "transducer",
    # "transforms",
    # "transacqua",
    # "translunar",
    # "translucid",
    # "transients",
    # "transcribe",
    # "retransmit",
    # "transships",
    # "translated",
    # "transmuted",
    # "transaxles",
    # "transition",
    # "transpired",
    # "transports",
    # "transpolar",
    # "transposed",
    # "transunion",
    # "translator",
    # "transvalue",
    # "transistor",
    # "transiliac",
    # "transitron",
    # "transfused",
    # "transpiler",
    # "transfrete",
    # "transactor",
    # "transprint",
    # "transshape",
    # "transience",
    # "transfects",
    # "transwoman",
    # "transduces",
    # "transobuoy",
    # "transfixes",
    # "transgress",
    # "transferal",
    # "transhuman",
    # "transeptal",
    # "airtransse",
    # "transmutes",
    # "transiency",
    # "transpubic",
    # "transfixed",
    # "transradar",
    # "transplant",
    # "fortransit",
    # "creditrans",
    # "transmuter",
    # "transigere",
    # "transposes",
    # "transpires",
    # "transgredi",
    # "trans peak",
    # "transcends",
    # "alptransit",
    # "transflash",
    # "transgenes",
    # "transgenic",
    # "transudate",
    # "transsonic",
    # "transputer",
    # "transposing",
    # "transversal",
    # "translucent",
    # "transferees",
    # "transgenics",
    # "translators",
    # "transcended",
    # "transfinite",
    # "transsummer",
    # "transecting",
    # "transracial",
    # "transiently",
    # "transactors",
    # "transhipped",
    # "transmitter",
    # "transfigure",
    # "transfected",
    # "transhumant",
    # "translation",
    # "transforate",
    # "translocate",
    # "translating",
    # "transcriber",
    # "transilient",
    # "transcripts",
    # "transfusive",
    # "transitions",
    # "transmutual",
    # "transferrin",
    # "transformer",
    # "transferred",
    # "transcribed",
    # "cotransport",
    # "transuranic",
    # "transporter",
    # "transdermal",
    # "transposons",
    # "transudates",
    # "transferral",
    # "transplants",
    # "transcalent",
    # "retranslate",
    # "transmarine",
    # "transmeable",
    # "transmitted",
    # "transalpine",
    # "transnature",
    # "transcoding",
    # "transducers",
    # "gender wage",
    # "translatory",
    # "transponder",
    # "transfixion",
    # "transvalued",
    # "transdermic",
    # "intransient",
    # "retransform",
    # "transferase",
    # "transported",
    # "translative",
    # "transacting",
    # "transfusing",
    # "transmuting",
    # "transducing",
    # "transpierce",
    # "transfixing",
    # "transformed",
    # "transverter",
    # "transferors",
    # "retransmits",
    # "transistors",
    # "transection",
    # "transocular",
    # "transpadane",
    # "transportal",
    # "transrectal",
    # "transmittal",
    # "transpiring",
    # "transferrer",
    # "transceiver",
    # "transfusion",
    # "transiences",
    # "translunary",
    # "transcribes",
    # "transvalues",
    # "transjordan",
    # "transfluent",
    # "transaction",
    # "transparent",
    # "transcolate",
    # "transonance",
    # "transpirate",
    # "transpennine",
    # "transparency",
    # "transference",
    # "transparence",
    # "transitivity",
    # "transmitters",
    # "transfecting",
    # "transferable",
    # "transections",
    # "transcursion",
    # "transcending",
    # "transvaluing",
    # "transiencies",
    # "transpicuous",
    # "transcribing",
    # "retranslates",
    # "transhumance",
    # "transferrers",
    # "translocated",
    # "transduction",
    # "transmigrant",
    # "transcranial",
    # "transgressed",
    # "transitively",
    # "transpierced",
    # "transferring",
    # "transcribers",
    # "transaminase",
    # "transmissive",
    # "transmittals",
    # "transfusable",
    # "transpacific",
    # "transluminal",
    # "transporters",
    # "transponders",
    # "transversion",
    # "transmundane",
    # "translucence",
    # "transplanted",
    # "gender roles",
    # "translucency",
    # "ditransitive",
    # "transmigrate",
    # "transceivers",
    # "transitional",
    # "transfigured",
    # "transfigures",
    # "transferases",
    # "transgresses",
    # "transelement",
    # "transmission",
    # "transmogrify",
    # "translatable",
    # "transcurrent",
    # "transvestism",
    # "transversals",
    # "transfection",
    # "transdialect",
    # "mistranslate",
    # "transgenesis",
    # "transductant",
    # "transactions",
    # "transforming",
    # "transudation",
    # "transporting",
    # "translocates",
    # "transuranium",
    # "transmitting",
    # "translations",
    # "transmutable",
    # "transmontane",
    # "transversely",
    # "transshipped",
    # "transgressor",
    # "translocator",
    # "untranslated",
    # "transpierces",
    # "transhipping",
    # "transitorily",
    # "transpontine",
    # "transoceanic",
    # "retranslated",
    # "transfixions",
    # "transposable",
    # "transfusions",
    # "intransitive",
    # "transcendent",
    # "transplanter",
    # "transvestite",
    # "transformers",
    # "transfusible",
    # "intransigent",
    # "transcaucasia",
    # "mistranslates",
    # "transactivate",
    # "transformable",
    # "transfections",
    # "transthoracic",
    # "transmittance",
    # "transylvanian",
    # "mistranslated",
    # "transgressive",
    # "transmittable",
    # "transnatation",
    # "transplanting",
    # "transmissible",
    # "transpiercing",
    # "transferrible",
    # "transportment",
    # "transcolation",
    # "transvestites",
    # "transistorise",
    # "transmissions",
    # "translucently",
    # "trans-pacific",
    # "intranscalent",
    # "translucences",
    # "transportance",
    # "retranslating",
    # "transcription",
    # "transaminases",
    # "transcatheter",
    # "transferrence",
    # "transductions",
    # "retransmitted",
    # "transcribbler",
    # "transmutative",
    # "transmembrane",
    # "transshipment",
    # "transactinide",
    # "transplendent",
    # "intransigeant",
    # "intransigence",
    # "transcendency",
    # "intransigents",
    # "transnational",
    # "transgressing",
    # "translocating",
    # "translational",
    # "transcriptase",
    # "transactional",
    # "translocation",
    # "transferrable",
    # "transparently",
    # "transmittancy",
    # "transudations",
    # "transliterate",
    # "transmigrated",
    # "transcriptive",
    # "transposition",
    # "transmigrante",
    # "nontransitive",
    # "transurethral",
    # "transpositive",
    # "gender equity",
    # "transcriptome",
    # "transpiration",
    # "transatlantic",
    # "transfeminate",
    # "transcultural",
    # "transgressors",
    # "transfusional",
    # "intransigency",
    # "transplanters",
    # "transistorize",
    # "transmittible",
    # "transmutation",
    # "transpalatine",
    # "trans-america",
    # "transshipping",
    # "turtle gender",
    # "transmigrates",
    # "transgression",
    # "transcurrence",
    # "transmigrator",
    # "retranslation",
    # "transcendence",
    # "transportable",
    # "transfiguring",
    # "transpersonal",
    # "transcutaneous",
    # "transistorises",
    # "untransmutable",
    # "autotransplant",
    # "transitiveness",
    # "transgressions",
    # "translatitious",
    # "transistorized",
    # "translocations",
    # "gender pay gap",
    # "intransigentes",
    # "trans atlantic",
    # "transparencies",
    # "transcendently",
    # "transmigratory",
    # "retransmission",
    # "transferential",
    # "transportation",
    # "intransigently",
    # "transcriptions",
    # "transsulfurase",
    # "transcorporate",
    # "homotransplant",
    # "subtranslucent",
    # "transmittivity",
    # "detransitivize",
    # "intransigences",
    # "transcapillary",
    # "transitionally",
    # "transpositions",
    # "transsegmental",
    # "intransmutable",
    # "transcendental",
    # "transfretation",
    # "transmethylase",
    # "retranslations",
    # "transtentorial",
    # "untransferable",
    # "intransitively",
    # "transductional",
    # "transanimation",
    # "transistorised",
    # "transmissivity",
    # "xenotransplant",
    # "impertransible",
    # "transplendency",
    # "transamination",
    # "transpatronize",
    # "transplacental",
    # "mistranslation",
    # "transmutations",
    # "transmigrators",
    # "transmittances",
    # "transliterates",
    # "translatorship",
    # "transliterated",
    # "transitoriness",
    # "intransitivise",
    # "retransmitting",
    # "transplantable",
    # "mistranslating",
    # "translucencies",
    # "intransitivize",
    # "transistorizes",
    # "transabdominal",
    # "transverberate",
    # "intransitivity",
    # "transformation",
    # "transmogrified",
    # "transcendences",
    # "detransitivise",
    # "transformative",
    # "subtransparent",
    # "transmigrating",
    # "transmogrifies",
    # "transshipments",
    # "allotransplant",
    # "transdniestria",
    # "transpirations",
    # "transpeptidase",
    # "transvaluation",
    # "transregionate",
    # "untranslatable",
    # "transvestitism",
    # "transmigration",
    # "transportingly",
    # "gender of nouns",
    # "transfiguration",
    # "turtles' gender",
    # "transformerless",
    # "trans logistics",
    # "transistor radio",
    # "transcontinental",
    # "gender price gap",
    # "gendered language",
    # "transition metals",
    # "gender performance",
    # "transubstantiation",
    # "gendered marketing",
    # "transformers prime",
    # "transformers movie",
    # "gender reassignment",
    # "diphosphotransferase",
    # "transitioning states",
    # "transversourethralis",
    # "transdifferentiation",
    # "transphosphorylation",
    # "carboxyltransferases",
    # "carbamoyltransferase",
    # "costotransversectomy",
    # "gender and ethnicity",
    # "pentosyltransferases",
    # "transfusion reaction",
    # "autotransplantations",
    # "galactosyltransferase",
    # "carbamoyltransferases",
    # "heterotransplantation",
    # "gender reveal parties",
    # "aminoacyltransferases",
    # "phosphotransacetylase",
    # "nucleotidyltransferase",
    # "transphosphoribosidase",
    # "glucuronosyltransferase",
    # "transitional government",
    # "pyrophosphotransferases",
    # "transubstantiationalist",
    "nucleotidyltransferases",
    "gender of a noun changes",
    "transureteroureterostomy",
    "deoxyribosyltransferases",
    "racial and gender equality",
]
irrelevant_for_anti_keywords = []
ANTI_KEYWORDS = [
    # "electric aircraft",
    # "car",
    # "spice girls",
    # "sex slave",
    # "transport",
    # "gender of nouns",
    # "gender of a noun changes",
]

OGS_KEYWORDS = {}
KEYWORD_SYNONYMS = {}
