KEYWORDS = [
    "transphobia",
    "transphobic",
    "anti-trans",
    "trans hate",
    "trans exclusion",
    "trans rights violation",
    "trans discrimination",
    "trans ",
    "trans-",
    "transgender",
    "trans people",
    "trans community",
    "gender-",
    "trans issues",
    "trans rights",
    "non binary",
    "non-binary",
    "gender non-conforming",
    "gender identity",
    "trans advocacy",
    "trans-inclusive",
    "misgendering",
    "deadnaming",
    "gender-critical feminism",
    "trans-exclusionary radical feminist",
    "terf ",
    "trans exclusionary feminism",
    "gender critical",
    "adult human female",
    "trans identified males",
    "Transology",
    "misgendered",
    "gender-critical",
    "trans breast milk",
    "Hormone blockers",
    "puberty blockers",
    "Tranvestia",
    "transmedicalism",
    "gender ",
    "trans man",
    "trans woman",
    "trans.",
    "trans?",
    "trans,",
    "Cass Review",
    "hilary cass",
    "cass report",
    "wrong body",
    "transsexual",
]
EXT_KEYWORDS = [
    "demimasc",
    "demigirl",
    "demiboy",
    "demifluid",
    "demiflux",
    "demigender",
    "demiguy",
    "demigal",
    "demienby",
    "gender agnostic",
    "intersex woman",
    "intersex man",
    "intersex person",
    "intersex people",
    "intersex",
    "vakasalewalewa",
    "genderfluid",
    "gender queer",
    "gender-queer",
    "genderqueer",
    "genderqueer person",
    "genderqueer people",
    "fakafifine",
    "androgyne",
    "androgynous",
    "androgynous person",
    "androgynous people",
    "bigender",
    "bigender person",
    "cisgender",
    "x-gender",
    "cogenitor",
    "altersex",
    "assigned female at birth",
    "neutral sex",
    "assigned at birth",
    "transmasculine",
    "genderfluid",
    "travesti",
    "hermaphroditism",
    "cisgender man",
    "cisgender woman",
    "genderqueer",
    "takatāpui",
    "androgynos",
    "'akava'ine",
    "māhū",
    "muxe",
    "faʻafafine",
    "shapeshifter",
    "futanari",
    "fakaleitī",
    "agender",
    "hijra",
    "kathoey",
    "two spirit",
    "androgyny",
    # "queer",
    "third gender",
    "third-gender",
    "non-binary",
    "trannies",
    "tranny",
    "women-only",
    "women only",
    "LGB"
]

OGS_KEYWORDS = []

irrelevant_for_keywords = [
    "transcended",
    "transfer",
    "transport",
    "transportation",
    "transporting",
    "transition",
    "transfusion",
    "transpennine",
    "transam",
    "transformative",
    "transplant",
    "sustrans",
    "transient",
    "transferred",
    "transit",
    "transatlantic",
    "trans atlantic",
    "trans-atlantic",
]

irrelevant_for_anti_keywords = []
ANTI_KEYWORDS = [
    "electric aircraft",
    "car",
    "spice girls"
]
Little_List = KEYWORDS + EXT_KEYWORDS
BIG_LIST = KEYWORDS + EXT_KEYWORDS + OGS_KEYWORDS
